import { useEffect, useMemo, useState } from 'react'
import logo from './assets/logo.png'
import { LANGUAGES, getDir, makeT } from './i18n'
// This module is generated by Wails ("wails dev" / "wails build") from the
// exported methods on the App struct in app.go. It won't exist until then.
import {
  ListProfiles,
  AddProfileFromLink,
  AddSubscription,
  DeleteProfile,
  RenameProfile,
  Connect,
  Disconnect,
  Status,
  Version,
  TestConnection,
  RecentLog,
  CheckForUpdate,
  ApplyUpdate,
  Platform,
  IsElevated,
  RestartElevated,
} from '../wailsjs/go/main/App'

function errorText(err) {
  if (!err) return 'Unknown error'
  if (typeof err === 'string') return err
  if (err.message) return err.message
  return String(err)
}

function openExternal(url) {
  if (window.runtime && window.runtime.BrowserOpenURL) {
    window.runtime.BrowserOpenURL(url)
  } else {
    window.open(url, '_blank')
  }
}

// Windows' emoji font (Segoe UI Emoji) doesn't render regional-indicator
// flag emoji -- it falls back to showing the two letters instead. Use an
// actual flag image so this looks right cross-platform.
function flagIconUrl(countryCode) {
  if (!countryCode || countryCode.length !== 2) return ''
  return `https://flagcdn.com/24x18/${countryCode.toLowerCase()}.png`
}

function Icon({ path, className = 'w-5 h-5' }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <path d={path} />
    </svg>
  )
}

const icons = {
  globe: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM3.6 9h16.8M3.6 15h16.8M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18',
  plus: 'M12 5v14M5 12h14',
  search: 'm21 21-4.3-4.3M18.5 11a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z',
  trash: 'M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13M10 11v6M14 11v6',
  pencil: 'M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4Z',
  power: 'M12 3v9M18.4 6.6a8.5 8.5 0 1 1-12.8 0',
  gauge: 'M12 8v4l3 2M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z',
  terminal: 'm5 6 5 5-5 5M13 17h6',
  info: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM12 16v-5h-1M11.94 8h.01',
  x: 'M6 6l12 12M18 6 6 18',
  sun: 'M12 17a5 5 0 1 0 0-10 5 5 0 0 0 0 10ZM12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4',
  moon: 'M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z',
  download: 'M12 3v12m0 0-4-4m4 4 4-4M4 21h16',
  shield: 'M12 3 5 6v5c0 4.5 3 7.7 7 9 4-1.3 7-4.5 7-9V6l-7-3Z',
  router: 'M4 15h16v4H4z M4 19v0 M20 19v0 M8 15V9a4 4 0 0 1 8 0v6 M12 3v2',
  translate: 'M4 5h7M9 3v2M9 5a10.4 10.4 0 0 1-4 8M3 9c0 3 3 5.5 6 6M12 20l4-9 4 9M13.5 17h5',
}

function StatusDot({ state }) {
  const color =
    state === 'running' ? 'bg-emerald-400' : state === 'starting' ? 'bg-amber-400' : state === 'error' ? 'bg-red-400' : 'bg-neutral-600'
  return <span className={`inline-block w-2 h-2 rounded-full ${color}`} />
}

function IconButton({ onClick, title, active, children }) {
  return (
    <button
      className={`w-9 h-9 rounded-lg flex items-center justify-center transition-colors ${
        active ? 'bg-[var(--bg-elevated)] text-[var(--accent)]' : 'text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)]'
      }`}
      title={title}
      onClick={onClick}
    >
      {children}
    </button>
  )
}

function ServerRow({ s, isSelected, isRunning, editingId, editingName, setEditingName, onSelect, onStartEdit, onCommitEdit, onCancelEdit, onDelete, t }) {
  const isActive = isSelected && isRunning
  return (
    <div
      onClick={onSelect}
      className={`group rounded-lg px-3 py-2.5 cursor-pointer border transition-colors ${
        isSelected
          ? 'bg-[var(--accent)]/10 border-[var(--accent)]/50'
          : 'bg-[var(--bg-panel)] border-transparent hover:bg-[var(--bg-hover)] hover:border-[var(--border)]'
      }`}
    >
      <div className="flex items-center justify-between gap-2">
        <div className="min-w-0 flex-1">
          {editingId === s.id ? (
            <input
              autoFocus
              className="text-sm font-medium bg-[var(--bg-elevated)] border border-[var(--border-strong)] rounded px-1 py-0.5 w-full"
              value={editingName}
              onChange={(e) => setEditingName(e.target.value)}
              onClick={(e) => e.stopPropagation()}
              onBlur={onCommitEdit}
              onKeyDown={(e) => {
                if (e.key === 'Enter') onCommitEdit()
                if (e.key === 'Escape') onCancelEdit()
              }}
            />
          ) : (
            <div className="flex items-center gap-1.5">
              {isActive && <StatusDot state="running" />}
              <div className="text-sm font-medium truncate">{s.name}</div>
            </div>
          )}
          <div className="text-[11px] text-[var(--text-faint)] truncate mt-0.5">
            {s.protocol} · {s.address}:{s.port}
          </div>
        </div>
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity shrink-0">
          <button
            className="w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)] flex items-center justify-center"
            onClick={onStartEdit}
            title={t('rename')}
          >
            <Icon path={icons.pencil} className="w-3.5 h-3.5" />
          </button>
          <button
            className="w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--danger)] hover:bg-[var(--danger-bg)] flex items-center justify-center"
            onClick={onDelete}
            title={t('remove')}
          >
            <Icon path={icons.trash} className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
    </div>
  )
}

export default function App() {
  const [servers, setServers] = useState([])
  const [link, setLink] = useState('')
  const [addOpen, setAddOpen] = useState(false)
  const [status, setStatus] = useState({ state: 'stopped' })
  const [error, setError] = useState('')
  const [selectedId, setSelectedId] = useState(null)
  const [pending, setPending] = useState(false)
  const [version, setVersion] = useState('')
  const [editingId, setEditingId] = useState(null)
  const [editingName, setEditingName] = useState('')
  const [query, setQuery] = useState('')
  const [testResult, setTestResult] = useState(null)
  const [testing, setTesting] = useState(false)
  const [log, setLog] = useState('')
  const [showLog, setShowLog] = useState(false)
  const [aboutOpen, setAboutOpen] = useState(false)
  const [theme, setTheme] = useState(() => {
    try {
      return localStorage.getItem('kite-theme') || 'dark'
    } catch {
      return 'dark'
    }
  })
  const [updateInfo, setUpdateInfo] = useState(null)
  const [updateDismissed, setUpdateDismissed] = useState(false)
  const [updating, setUpdating] = useState(false)
  const [updateError, setUpdateError] = useState('')
  const [checkingUpdate, setCheckingUpdate] = useState(false)
  const [updateProgress, setUpdateProgress] = useState(null)
  const [mode, setMode] = useState('proxy')
  const [platform, setPlatform] = useState('')
  const [elevated, setElevated] = useState(true)
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem('kite-lang') || 'en'
    } catch {
      return 'en'
    }
  })
  const [langOpen, setLangOpen] = useState(false)
  const t = useMemo(() => makeT(lang), [lang])

  useEffect(() => {
    document.documentElement.setAttribute('dir', getDir(lang))
    document.documentElement.setAttribute('data-lang', lang)
    try {
      localStorage.setItem('kite-lang', lang)
    } catch {
      // ignore (private browsing / storage disabled)
    }
  }, [lang])

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme)
    try {
      localStorage.setItem('kite-theme', theme)
    } catch {
      // ignore (private browsing / storage disabled)
    }
  }, [theme])

  useEffect(() => {
    ListProfiles()
      .then((list) => {
        setServers(list || [])
        if (list && list.length > 0) setSelectedId(list[0].id)
      })
      .catch((err) => setError(errorText(err)))
    Status().then(setStatus).catch(() => {})
    Version().then(setVersion).catch(() => {})
    CheckForUpdate().then(setUpdateInfo).catch(() => {})
    Platform().then(setPlatform).catch(() => {})
    IsElevated().then(setElevated).catch(() => {})

    if (window.runtime && window.runtime.EventsOn) {
      const off = window.runtime.EventsOn('update:progress', (p) => setUpdateProgress(p))
      return off
    }
  }, [])

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    if (!q) return servers
    return servers.filter(
      (s) => s.name?.toLowerCase().includes(q) || s.address?.toLowerCase().includes(q) || s.protocol?.toLowerCase().includes(q),
    )
  }, [servers, query])

  // Servers imported from a subscription URL all share the same
  // extra.subGroup id -- fold those into one collapsible row instead of
  // flooding the list (a subscription can carry hundreds of servers).
  const { standalone, groups } = useMemo(() => {
    const groupMap = new Map()
    const standalone = []
    for (const s of filtered) {
      const groupId = s.extra?.subGroup
      if (!groupId) {
        standalone.push(s)
        continue
      }
      if (!groupMap.has(groupId)) {
        groupMap.set(groupId, { id: groupId, name: s.extra?.subGroupName || 'Subscription', servers: [] })
      }
      groupMap.get(groupId).servers.push(s)
    }
    return { standalone, groups: [...groupMap.values()] }
  }, [filtered])

  const [expandedGroups, setExpandedGroups] = useState(() => new Set())
  const searching = query.trim().length > 0
  function toggleGroup(id) {
    setExpandedGroups((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  const selected = servers.find((s) => s.id === selectedId) || null
  const isRunning = status.state === 'running'
  const isBusy = pending || status.state === 'starting'

  async function handleAddLink() {
    const value = link.trim()
    if (!value) return
    setError('')
    try {
      if (/^https?:\/\//i.test(value)) {
        const added = await AddSubscription(value)
        setServers((prev) => [...prev, ...added])
        if (added.length > 0) setSelectedId(added[added.length - 1].id)
      } else {
        const server = await AddProfileFromLink(value)
        setServers((prev) => [...prev, server])
        setSelectedId(server.id)
      }
      setLink('')
      setAddOpen(false)
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleToggle() {
    setError('')
    setTestResult(null)
    if (isRunning) {
      setPending(true)
      try {
        await Disconnect()
        setStatus(await Status())
      } catch (err) {
        setError(errorText(err))
      } finally {
        setPending(false)
      }
      return
    }

    if (!selected) {
      setError(t('addServerFirst'))
      return
    }
    setPending(true)
    try {
      await Connect(selected.id, mode)
      setStatus(await Status())
      handleTest()
    } catch (err) {
      setError(errorText(err))
      setStatus(await Status().catch(() => ({ state: 'stopped' })))
    } finally {
      setPending(false)
    }
  }

  async function handleRestartElevated() {
    setError('')
    try {
      await RestartElevated()
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleDelete(id, e) {
    e.stopPropagation()
    setError('')
    try {
      await DeleteProfile(id)
      setServers((prev) => prev.filter((s) => s.id !== id))
      if (selectedId === id) setSelectedId(null)
    } catch (err) {
      setError(errorText(err))
    }
  }

  function startEditing(server, e) {
    e.stopPropagation()
    setEditingId(server.id)
    setEditingName(server.name)
  }

  async function commitEditing(id) {
    const name = editingName.trim()
    setEditingId(null)
    if (!name) return
    setError('')
    try {
      const updated = await RenameProfile(id, name)
      setServers((prev) => prev.map((s) => (s.id === id ? updated : s)))
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleTest() {
    setTesting(true)
    setTestResult(null)
    try {
      const result = await TestConnection()
      setTestResult({ ok: true, ...result })
    } catch (err) {
      setTestResult({ ok: false, text: errorText(err) })
    } finally {
      setTesting(false)
    }
  }

  async function handleShowLog() {
    setShowLog((prev) => !prev)
    try {
      setLog(await RecentLog())
    } catch (err) {
      setLog(errorText(err))
    }
  }

  async function handleCheckUpdate() {
    setCheckingUpdate(true)
    setUpdateError('')
    try {
      const info = await CheckForUpdate()
      setUpdateInfo(info)
      setUpdateDismissed(false)
    } catch (err) {
      setUpdateError(errorText(err))
    } finally {
      setCheckingUpdate(false)
    }
  }

  async function handleUpdate() {
    setUpdating(true)
    setUpdateError('')
    setUpdateProgress(null)
    try {
      // ApplyUpdate only returns on failure -- on success the process
      // exits and relaunches before this promise would ever resolve.
      await ApplyUpdate()
    } catch (err) {
      setUpdateError(errorText(err))
      setUpdating(false)
      setUpdateProgress(null)
    }
  }

  const showUpdateBanner = updateInfo?.available && !updateDismissed
  const progressPct =
    updateProgress && updateProgress.total > 0 ? Math.min(100, Math.round((updateProgress.downloaded / updateProgress.total) * 100)) : null

  return (
    <div className="h-screen flex flex-col bg-[var(--bg)] text-[var(--text)] overflow-hidden">
      {showUpdateBanner && (
        <div className="flex flex-col shrink-0">
          <div className="flex items-center gap-3 px-4 py-2 bg-[var(--accent)] text-[var(--accent-text)] text-sm">
            <Icon path={icons.download} className="w-4 h-4 shrink-0" />
            <span className="flex-1">
              {updating
                ? progressPct !== null
                  ? t('downloadingUpdatePct', progressPct)
                  : t('downloadingUpdate')
                : t('updateAvailableBanner', updateInfo.latest, updateInfo.current || version)}
            </span>
            {!updating && (
              <button
                onClick={handleUpdate}
                className="rounded-md bg-white/20 hover:bg-white/30 px-3 py-1 text-xs font-medium transition-colors"
              >
                {t('updateNow')}
              </button>
            )}
            {!updating && (
              <button onClick={() => setUpdateDismissed(true)} className="text-white/70 hover:text-white">
                <Icon path={icons.x} className="w-4 h-4" />
              </button>
            )}
          </div>
          {updating && (
            <div className="h-1 bg-black/20">
              <div
                className="h-full bg-white/80 transition-all duration-150"
                style={{ width: progressPct !== null ? `${progressPct}%` : '30%' }}
              />
            </div>
          )}
        </div>
      )}
      {updateError && (
        <div className="px-4 py-1.5 bg-[var(--danger-bg)] text-[var(--danger)] text-xs shrink-0">{t('updateFailed', updateError)}</div>
      )}

      <div className="flex-1 flex overflow-hidden">
        {/* Icon rail */}
        <aside className="w-14 flex flex-col items-center py-4 gap-4 bg-[var(--bg-panel)] border-r border-[var(--border)] shrink-0">
          <img src={logo} alt="Kite" className="w-8 h-8 rounded-lg" />
          <IconButton active title={t('servers')}>
            <Icon path={icons.globe} className="w-5 h-5" />
          </IconButton>
          <IconButton title={showLog ? t('hideLog') : t('showLog')} onClick={handleShowLog}>
            <Icon path={icons.terminal} className="w-5 h-5" />
          </IconButton>
          <IconButton title={t('about')} onClick={() => setAboutOpen(true)}>
            <Icon path={icons.info} className="w-5 h-5" />
          </IconButton>
          <div className="relative">
            <IconButton title={t('language')} onClick={() => setLangOpen((v) => !v)}>
              <Icon path={icons.translate} className="w-5 h-5" />
            </IconButton>
            {langOpen && (
              <>
                <div className="fixed inset-0 z-40" onClick={() => setLangOpen(false)} />
                <div className="absolute left-11 bottom-0 z-50 w-40 rounded-lg border border-[var(--border)] bg-[var(--bg-panel)] shadow-lg py-1">
                  {LANGUAGES.map((l) => (
                    <button
                      key={l.code}
                      onClick={() => {
                        setLang(l.code)
                        setLangOpen(false)
                      }}
                      className={`w-full text-left px-3 py-1.5 text-sm transition-colors ${
                        lang === l.code ? 'text-[var(--accent)] bg-[var(--bg-elevated)]' : 'text-[var(--text-dim)] hover:bg-[var(--bg-hover)]'
                      }`}
                    >
                      {l.label}
                    </button>
                  ))}
                </div>
              </>
            )}
          </div>
          <div className="flex-1" />
          <IconButton title={theme === 'dark' ? t('switchToLight') : t('switchToDark')} onClick={() => setTheme((th) => (th === 'dark' ? 'light' : 'dark'))}>
            <Icon path={theme === 'dark' ? icons.sun : icons.moon} className="w-5 h-5" />
          </IconButton>
        </aside>

        {/* Server list */}
        <section className="w-80 border-r border-[var(--border)] flex flex-col shrink-0">
          <div className="p-4 border-b border-[var(--border)]">
            <h1 className="text-lg font-semibold mb-3">Kite</h1>
            <div className="flex items-center gap-2">
              <div className="relative flex-1">
                <Icon path={icons.search} className="w-4 h-4 absolute left-2.5 top-1/2 -translate-y-1/2 text-[var(--text-faint)]" />
                <input
                  className="w-full rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)] pl-8 pr-2 py-2 text-sm placeholder:text-[var(--text-faint)] focus:outline-none focus:border-[var(--accent)]"
                  placeholder={t('searchServers')}
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                />
              </div>
              <button
                className="w-9 h-9 shrink-0 rounded-lg bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-[var(--accent-text)] flex items-center justify-center transition-colors"
                title={t('addServer')}
                onClick={() => setAddOpen((v) => !v)}
              >
                <Icon path={icons.plus} className="w-4 h-4" />
              </button>
            </div>

            {addOpen && (
              <div className="flex gap-2 mt-3">
                <input
                  autoFocus
                  className="flex-1 rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)] px-3 py-2 text-xs placeholder:text-[var(--text-faint)] focus:outline-none focus:border-[var(--accent)]"
                  placeholder={t('addLinkPlaceholder')}
                  value={link}
                  onChange={(e) => setLink(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleAddLink()}
                />
                <button
                  className="rounded-lg bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-[var(--accent-text)] px-3 text-xs font-medium transition-colors"
                  onClick={handleAddLink}
                >
                  {t('add')}
                </button>
              </div>
            )}
          </div>

          <div className="flex-1 overflow-y-auto p-2 space-y-1">
            {filtered.length === 0 && (
              <div className="text-center text-[var(--text-faint)] text-xs mt-10 px-4">
                {servers.length === 0 ? t('noServersYet') : t('noMatches')}
              </div>
            )}
            {standalone.map((s) => (
              <ServerRow
                key={s.id}
                s={s}
                isSelected={s.id === selectedId}
                isRunning={isRunning}
                editingId={editingId}
                editingName={editingName}
                setEditingName={setEditingName}
                onSelect={() => setSelectedId(s.id)}
                onStartEdit={(e) => startEditing(s, e)}
                onCommitEdit={() => commitEditing(s.id)}
                onCancelEdit={() => setEditingId(null)}
                onDelete={(e) => handleDelete(s.id, e)}
                t={t}
              />
            ))}
            {groups.map((g) => {
              const isOpen = searching || expandedGroups.has(g.id)
              const activeInGroup = g.servers.some((s) => s.id === selectedId)
              return (
                <div key={g.id} className="space-y-1">
                  <div
                    onClick={() => toggleGroup(g.id)}
                    className={`flex items-center gap-2 rounded-lg px-3 py-2.5 cursor-pointer border transition-colors ${
                      activeInGroup
                        ? 'bg-[var(--accent)]/10 border-[var(--accent)]/50'
                        : 'bg-[var(--bg-panel)] border-transparent hover:bg-[var(--bg-hover)] hover:border-[var(--border)]'
                    }`}
                  >
                    <Icon
                      path="m9 18 6-6-6-6"
                      className={`w-3.5 h-3.5 shrink-0 text-[var(--text-faint)] transition-transform ${isOpen ? 'rotate-90' : ''}`}
                    />
                    <div className="min-w-0 flex-1">
                      <div className="text-sm font-medium truncate">{g.name}</div>
                      <div className="text-[11px] text-[var(--text-faint)] truncate mt-0.5">{g.servers.length} servers</div>
                    </div>
                  </div>
                  {isOpen && (
                    <div className="pl-3 space-y-1 border-l border-[var(--border)] ml-4">
                      {g.servers.map((s) => (
                        <ServerRow
                          key={s.id}
                          s={s}
                          isSelected={s.id === selectedId}
                          isRunning={isRunning}
                          editingId={editingId}
                          editingName={editingName}
                          setEditingName={setEditingName}
                          onSelect={() => setSelectedId(s.id)}
                          onStartEdit={(e) => startEditing(s, e)}
                          onCommitEdit={() => commitEditing(s.id)}
                          onCancelEdit={() => setEditingId(null)}
                          onDelete={(e) => handleDelete(s.id, e)}
                          t={t}
                        />
                      ))}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </section>

        {/* Connect panel */}
        <main className="flex-1 flex flex-col items-center justify-center gap-6 p-8 relative overflow-y-auto">
          <div className="text-center">
            <div className="text-sm text-[var(--text-dim)]">{selected ? selected.name : t('noServerSelected')}</div>
            {selected && (
              <div className="text-xs text-[var(--text-faint)] mt-0.5">
                {selected.protocol} · {selected.address}:{selected.port}
              </div>
            )}
          </div>

          {platform === 'windows' && !isRunning && (
            <div className="flex items-center rounded-lg bg-[var(--bg-panel)] border border-[var(--border)] p-1 text-xs">
              <button
                onClick={() => setMode('proxy')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md transition-colors ${
                  mode === 'proxy' ? 'bg-[var(--accent)] text-[var(--accent-text)]' : 'text-[var(--text-dim)] hover:text-[var(--text)]'
                }`}
              >
                <Icon path={icons.globe} className="w-3.5 h-3.5" />
                {t('proxy')}
              </button>
              <button
                onClick={() => setMode('tun')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md transition-colors ${
                  mode === 'tun' ? 'bg-[var(--accent)] text-[var(--accent-text)]' : 'text-[var(--text-dim)] hover:text-[var(--text)]'
                }`}
              >
                <Icon path={icons.router} className="w-3.5 h-3.5" />
                {t('tun')}
              </button>
            </div>
          )}

          {platform === 'windows' && mode === 'tun' && !elevated && !isRunning && (
            <div className="flex items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--bg-panel)] px-3 py-2 text-xs text-[var(--text-dim)]">
              <Icon path={icons.shield} className="w-4 h-4 shrink-0 text-[var(--text-faint)]" />
              <span>{t('tunNeedsAdmin')}</span>
              <button onClick={handleRestartElevated} className="text-[var(--accent)] hover:text-[var(--accent-hover)] font-medium shrink-0">
                {t('restartAsAdmin')}
              </button>
            </div>
          )}

          <button
            onClick={handleToggle}
            disabled={isBusy || (!isRunning && !selected) || (mode === 'tun' && !elevated && !isRunning)}
            className={`relative w-40 h-40 rounded-full flex items-center justify-center transition-all duration-300 disabled:opacity-40 disabled:cursor-not-allowed ${
              isRunning
                ? 'bg-[var(--accent)] shadow-[0_0_60px_-10px_rgba(99,102,241,0.7)]'
                : 'bg-[var(--bg-panel)] border border-[var(--border-strong)] hover:border-[var(--text-faint)]'
            }`}
          >
            {isBusy ? (
              <div className="w-8 h-8 border-2 border-[var(--text-faint)] border-t-transparent rounded-full animate-spin" />
            ) : (
              <Icon path={icons.power} className={`w-12 h-12 ${isRunning ? 'text-[var(--accent-text)]' : 'text-[var(--text-faint)]'}`} />
            )}
          </button>

          <div className="text-center">
            <div className="text-sm font-medium">
              {isBusy ? (isRunning ? t('disconnecting') : t('connecting')) : isRunning ? t('connected') : t('disconnected')}
            </div>
            {isRunning && (
              <div className="text-xs text-[var(--text-faint)] mt-1">
                {status.mode === 'tun' ? t('tunAdapterAllTraffic') : 'HTTP 127.0.0.1:2080 · SOCKS5 127.0.0.1:2081'}
              </div>
            )}
          </div>

          {isRunning && (
            <button
              onClick={handleTest}
              disabled={testing}
              className="flex items-center gap-1.5 text-xs text-[var(--text-dim)] hover:text-[var(--text)] disabled:opacity-50 transition-colors"
            >
              <Icon path={icons.gauge} className="w-3.5 h-3.5" />
              {testing ? t('testing') : t('testConnection')}
            </button>
          )}

          <div className="w-full max-w-sm space-y-2">
            {error && (
              <div className="rounded-lg border border-[var(--danger-border)] bg-[var(--danger-bg)] px-3 py-2 text-xs text-[var(--danger)] break-words">
                {error}
              </div>
            )}
            {testResult && testResult.ok && (
              <div className="rounded-lg border border-[var(--success-border)] bg-[var(--success-bg)] px-3 py-2 text-xs text-[var(--success)] flex items-center justify-center gap-2">
                {testResult.country && (
                  <img
                    src={flagIconUrl(testResult.country)}
                    alt={testResult.country}
                    className="w-4 h-3 rounded-sm object-cover"
                    onError={(e) => { e.currentTarget.style.display = 'none' }}
                  />
                )}
                <span className="font-medium">{testResult.ip}</span>
                {testResult.country && <span className="text-[var(--success)]/70">{testResult.country}</span>}
                <span className="text-[var(--success)]/70">·</span>
                <span>{testResult.delayMs}ms</span>
              </div>
            )}
            {testResult && !testResult.ok && (
              <div className="rounded-lg border border-[var(--danger-border)] bg-[var(--danger-bg)] px-3 py-2 text-xs text-[var(--danger)] break-words">
                ✗ {testResult.text}
              </div>
            )}
          </div>

          {showLog && (
            <pre className="w-full max-w-2xl max-h-64 overflow-auto rounded-lg border border-[var(--border)] bg-[var(--bg-panel)] p-3 text-[11px] text-[var(--text-faint)] whitespace-pre-wrap break-all">
              {log || t('logEmpty')}
            </pre>
          )}
        </main>
      </div>

      {aboutOpen && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setAboutOpen(false)}>
          <div
            className="w-full max-w-sm rounded-xl bg-[var(--bg-panel)] border border-[var(--border)] p-6 text-center"
            onClick={(e) => e.stopPropagation()}
          >
            <img src={logo} alt="Kite" className="w-14 h-14 rounded-xl mx-auto mb-3" />
            <h2 className="text-lg font-semibold">Kite</h2>
            <p className="text-xs text-[var(--text-faint)] mt-1">v{version.replace(/^v/, '')}</p>
            <p className="text-sm text-[var(--text-dim)] mt-4">
              {t('aboutDescription')}
            </p>

            <div
              className="mt-4 flex items-center justify-center gap-2 rounded-md border border-[var(--border-strong)] px-3 py-1.5 cursor-pointer hover:bg-[var(--bg-hover)] transition-colors"
              onClick={() => navigator.clipboard?.writeText('https://github.com/freeb5d/kite')}
              title={t('clickToCopy')}
            >
              <span className="text-xs text-[var(--accent)]">github.com/freeb5d/kite</span>
              <Icon path="M8 16H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2m-6 12h8a2 2 0 0 0 2-2v-8a2 2 0 0 0-2-2h-8a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2Z" className="w-3.5 h-3.5 text-[var(--text-faint)]" />
            </div>

            <div className="mt-3 flex items-center justify-center gap-4 text-xs">
              <button
                className="text-[var(--text-dim)] hover:text-[var(--accent)] underline underline-offset-2"
                onClick={() => openExternal('https://github.com/freeb5d/kite')}
              >
                {t('repository')}
              </button>
              <button
                className="text-[var(--text-dim)] hover:text-[var(--accent)] underline underline-offset-2"
                onClick={() => openExternal('https://github.com/freeb5d/kite/releases')}
              >
                {t('releases')}
              </button>
              <button
                className="text-[var(--text-dim)] hover:text-[var(--accent)] underline underline-offset-2"
                onClick={() => openExternal('https://github.com/freeb5d/kite/issues')}
              >
                {t('reportIssue')}
              </button>
            </div>

            <p className="mt-3 text-[10px] text-[var(--text-faint)]">
              {t('searchHint')}
            </p>

            <div className="mt-5 pt-4 border-t border-[var(--border)]">
              <button
                onClick={handleCheckUpdate}
                disabled={checkingUpdate}
                className="text-xs rounded-md border border-[var(--border-strong)] hover:bg-[var(--bg-hover)] px-3 py-1.5 disabled:opacity-50 transition-colors"
              >
                {checkingUpdate ? t('checking') : t('checkForUpdates')}
              </button>
              {updateInfo && (
                <p className="text-xs text-[var(--text-faint)] mt-2">
                  {updateInfo.available ? t('updateAvailable', updateInfo.latest) : t('onLatest')}
                </p>
              )}
            </div>

            <button
              className="mt-5 text-xs text-[var(--text-faint)] hover:text-[var(--text)]"
              onClick={() => setAboutOpen(false)}
            >
              {t('close')}
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
