import { useEffect, useState } from 'react'
// This module is generated by Wails ("wails dev" / "wails build") from the
// exported methods on the App struct in app.go. It won't exist until then.
import { ListProfiles, AddProfileFromLink, Connect, Disconnect, Status } from '../wailsjs/go/main/App'

export default function App() {
  const [servers, setServers] = useState([])
  const [link, setLink] = useState('')
  const [status, setStatus] = useState({ state: 'stopped' })

  useEffect(() => {
    ListProfiles().then(setServers).catch(() => {})
    Status().then(setStatus).catch(() => {})
  }, [])

  async function handleAddLink() {
    if (!link.trim()) return
    const server = await AddProfileFromLink(link.trim())
    setServers((prev) => [...prev, server])
    setLink('')
  }

  async function handleConnect(id) {
    await Connect(id)
    setStatus(await Status())
  }

  async function handleDisconnect() {
    await Disconnect()
    setStatus(await Status())
  }

  return (
    <div className="min-h-screen p-6 max-w-xl mx-auto">
      <h1 className="text-2xl font-semibold mb-4">Kite</h1>

      <div className="flex gap-2 mb-6">
        <input
          className="flex-1 rounded bg-neutral-900 border border-neutral-700 px-3 py-2 text-sm"
          placeholder="vmess:// vless:// trojan:// ss://"
          value={link}
          onChange={(e) => setLink(e.target.value)}
        />
        <button
          className="rounded bg-blue-600 hover:bg-blue-500 px-4 py-2 text-sm font-medium"
          onClick={handleAddLink}
        >
          Add
        </button>
      </div>

      <div className="mb-4 text-sm text-neutral-400">
        Status: <span className="font-medium text-neutral-200">{status.state}</span>
        {status.state === 'running' && (
          <button className="ml-3 text-red-400 hover:text-red-300" onClick={handleDisconnect}>
            Disconnect
          </button>
        )}
      </div>

      <ul className="space-y-2">
        {servers.map((s) => (
          <li
            key={s.id}
            className="flex items-center justify-between rounded bg-neutral-900 border border-neutral-800 px-3 py-2"
          >
            <div>
              <div className="text-sm font-medium">{s.name}</div>
              <div className="text-xs text-neutral-500">
                {s.protocol} · {s.address}:{s.port}
              </div>
            </div>
            <button
              className="rounded bg-neutral-800 hover:bg-neutral-700 px-3 py-1 text-xs"
              onClick={() => handleConnect(s.id)}
            >
              Connect
            </button>
          </li>
        ))}
      </ul>
    </div>
  )
}
