import { useEffect, useState } from 'react'
// This module is generated by Wails ("wails dev" / "wails build") from the
// exported methods on the App struct in app.go. It won't exist until then.
import {
  ListProfiles,
  AddProfileFromLink,
  DeleteProfile,
  RenameProfile,
  Connect,
  Disconnect,
  Status,
  Version,
} from '../wailsjs/go/main/App'

function errorText(err) {
  if (!err) return 'Unknown error'
  if (typeof err === 'string') return err
  if (err.message) return err.message
  return String(err)
}

export default function App() {
  const [servers, setServers] = useState([])
  const [link, setLink] = useState('')
  const [status, setStatus] = useState({ state: 'stopped' })
  const [error, setError] = useState('')
  const [connectingId, setConnectingId] = useState(null)
  const [version, setVersion] = useState('')
  const [editingId, setEditingId] = useState(null)
  const [editingName, setEditingName] = useState('')

  useEffect(() => {
    ListProfiles().then(setServers).catch((err) => setError(errorText(err)))
    Status().then(setStatus).catch(() => {})
    Version().then(setVersion).catch(() => {})
  }, [])

  async function handleAddLink() {
    if (!link.trim()) return
    setError('')
    try {
      const server = await AddProfileFromLink(link.trim())
      setServers((prev) => [...prev, server])
      setLink('')
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleConnect(id) {
    setError('')
    setConnectingId(id)
    try {
      await Connect(id)
      setStatus(await Status())
    } catch (err) {
      setError(errorText(err))
      setStatus(await Status().catch(() => ({ state: 'stopped' })))
    } finally {
      setConnectingId(null)
    }
  }

  async function handleDisconnect() {
    setError('')
    try {
      await Disconnect()
      setStatus(await Status())
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleDelete(id) {
    setError('')
    try {
      await DeleteProfile(id)
      setServers((prev) => prev.filter((s) => s.id !== id))
    } catch (err) {
      setError(errorText(err))
    }
  }

  function startEditing(server) {
    setEditingId(server.id)
    setEditingName(server.name)
  }

  async function commitEditing(id) {
    const name = editingName.trim()
    setEditingId(null)
    if (!name) return
    setError('')
    try {
      const updated = await RenameProfile(id, name)
      setServers((prev) => prev.map((s) => (s.id === id ? updated : s)))
    } catch (err) {
      setError(errorText(err))
    }
  }

  return (
    <div className="min-h-screen p-6 max-w-xl mx-auto">
      <h1 className="text-2xl font-semibold mb-4">Kite</h1>

      <div className="flex gap-2 mb-6">
        <input
          className="flex-1 rounded bg-neutral-900 border border-neutral-700 px-3 py-2 text-sm"
          placeholder="vmess:// vless:// trojan:// ss://"
          value={link}
          onChange={(e) => setLink(e.target.value)}
        />
        <button
          className="rounded bg-blue-600 hover:bg-blue-500 px-4 py-2 text-sm font-medium"
          onClick={handleAddLink}
        >
          Add
        </button>
      </div>

      <div className="mb-4 text-sm text-neutral-400">
        Status: <span className="font-medium text-neutral-200">{status.state}</span>
        {status.state === 'running' && (
          <button className="ml-3 text-red-400 hover:text-red-300" onClick={handleDisconnect}>
            Disconnect
          </button>
        )}
      </div>

      {error && (
        <div className="mb-4 rounded border border-red-800 bg-red-950 px-3 py-2 text-sm text-red-300 break-words">
          {error}
        </div>
      )}

      <ul className="space-y-2">
        {servers.map((s) => (
          <li
            key={s.id}
            className="flex items-center justify-between rounded bg-neutral-900 border border-neutral-800 px-3 py-2"
          >
            <div className="min-w-0">
              {editingId === s.id ? (
                <input
                  autoFocus
                  className="text-sm font-medium bg-neutral-800 border border-neutral-700 rounded px-1 py-0.5 w-full"
                  value={editingName}
                  onChange={(e) => setEditingName(e.target.value)}
                  onBlur={() => commitEditing(s.id)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') commitEditing(s.id)
                    if (e.key === 'Escape') setEditingId(null)
                  }}
                />
              ) : (
                <div
                  className="text-sm font-medium cursor-text"
                  title="Click to rename"
                  onClick={() => startEditing(s)}
                >
                  {s.name}
                </div>
              )}
              <div className="text-xs text-neutral-500">
                {s.protocol} · {s.address}:{s.port}
              </div>
            </div>
            <div className="flex gap-2 shrink-0">
              <button
                className="rounded bg-neutral-800 hover:bg-neutral-700 px-3 py-1 text-xs disabled:opacity-50"
                disabled={connectingId === s.id}
                onClick={() => handleConnect(s.id)}
              >
                {connectingId === s.id ? 'Connecting…' : 'Connect'}
              </button>
              <button
                className="rounded bg-neutral-800 hover:bg-red-900 hover:text-red-300 px-3 py-1 text-xs"
                onClick={() => handleDelete(s.id)}
              >
                Remove
              </button>
            </div>
          </li>
        ))}
      </ul>

      <footer className="fixed bottom-0 left-0 right-0 px-4 py-2 text-xs text-neutral-600 border-t border-neutral-900">
        Kite {version && `v${version.replace(/^v/, '')}`}
      </footer>
    </div>
  )
}
